name: Build

on:
  push:
    branches-ignore:
      - gh-readonly-queue/**
  pull_request:
  merge_group:

jobs:
  build-windows:
    runs-on: windows-latest
    env:
      CARGO_HTTP_MULTIPLEXING: false
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Install Vulkan SDK
      uses: humbletim/install-vulkan-sdk@v1.2
      with:
        version: 1.3.296.0
        cache: true

    - name: Build in release mode
      run: |
        mkdir release
        cd release
        cmake --version
        cmake -E env CXXFLAGS=/WX LDFLAGS=/WX cmake -A x64 -DEXCEPTION_HANDLING=ON -DVULKAN=ON -DCMAKE_BUILD_TYPE=Release -Werror=dev -DDOWNLOAD_GTEST=ON -DCMAKE_RUNTIME_OUTPUT_DIRECTORY_RELEASE=. ..
        cmake --build . --config Release --target everything

    - name: Package
      run: |
        cd release
        cmake --build . --config Release --target package_default
        mkdir artifacts
        mv *-win64.zip artifacts

    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ddnet-windows
        path: release/artifacts
